name: nfc_parking
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  fpdart: ^1.1.0
  equatable: ^2.0.5
  intl: ^0.19.0
  go_router: ^13.2.0
  get_it: ^7.6.7
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  fluentui_system_icons: ^1.1.229
  nfc_manager: ^3.3.0
  camera: ^0.10.5+9
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.0.1
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_text_recognition: ^0.11.0
  google_ml_kit: ^0.16.3
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/labels/
    - assets/models/
